#!/bin/sh
# 仅在wan/vwan接口下线时触发检测
case "$INTERFACE" in
	wan|vwan*) [ "$ACTION" = "ifdown" ] && pppconnectcheck & ;;
esac

wanselect=$(uci -q get syncdial.config.wanselect)
[ "$(uci -q get syncdial.config.dial_type)" = "2" ] && {
	wanselect2=$(uci -q get syncdial.config.wanselect2)
}

[ "$(uci -q get syncdial.config.enabled)" = "1" ] && \
	[ "$(uci -q get syncdial.config.old_frame)" = "1" ] && \
	[ "$DEVICE" = "$(uci -q get network.$wanselect.device || uci -q get network.$wanselect.ifname)" ] && \
	[ "$ACTION" = "ifup" ] && {
	ifname=$(uci -q get network.$wanselect.device || uci -q get network.$wanselect.ifname)
	wannum=$(uci -q get syncdial.config.wannum)
	for i in $(seq 1 $wannum)
	do
		[ -d /sys/class/net/macvlan$i ] || {
			ip link add link $ifname name macvlan$i type macvlan
			ip link set macvlan$i address $(echo $(cat /sys/class/net/$ifname/address|awk -F ":" '{print $1":"$2":"$3":"$4":"$5":" }')$(echo "" | awk -F ":" '{printf("%X\n", 16+i);}' i=$i))
			ip link set macvlan$i up
		}
	done

	[ "$(uci -q get syncdial.config.dial_type)" = "2" ] && {
	ifname2=$(uci -q get network.$wanselect2.device || uci -q get network.$wanselect2.ifname)
	wannum2=$(uci -q get syncdial.config.wannum2)
	for i in $(seq 1 $wannum2)
	do
		[ -d /sys/class/net/macvlan$(($wannum+$i)) ] || {
			ip link add link $ifname2 name macvlan$(($wannum+$i)) type macvlan
			ip link set macvlan$(($wannum+$i)) address $(echo $(cat /sys/class/net/$ifname2/address|awk -F ":" '{print $1":"$2":"$3":"$4":"$5":" }')$(echo "" | awk -F ":" '{printf("%X\n", 16+i);}' i=$i))
			ip link set macvlan$(($wannum+$i)) up
		}
	done
	}
}
